# Generated by Django 3.1.2 on 2020-11-05 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
    ]
